# Generated by Django 4.2.7 on 2023-11-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('official_name', models.CharField(max_length=100)),
                ('native_name', models.JSONField()),
                ('tld', models.CharField(max_length=10)),
                ('cca2', models.CharField(max_length=10)),
                ('ccn3', models.CharField(max_length=10)),
                ('cca3', models.CharField(max_length=10)),
                ('cioc', models.CharField(max_length=10)),
                ('fifa', models.CharField(max_length=10)),
                ('independent', models.BooleanField()),
                ('status', models.CharField(max_length=100)),
                ('un_member', models.BooleanField()),
                ('idd', models.JSONField()),
                ('capital', models.CharField(max_length=100)),
                ('capital_info', models.JSONField()),
                ('alt_spellings', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(max_length=100)),
                ('continents', models.JSONField()),
                ('languages', models.JSONField()),
                ('translations', models.JSONField()),
                ('latlng', models.JSONField()),
                ('landlocked', models.BooleanField()),
                ('borders', models.JSONField()),
                ('area', models.PositiveIntegerField()),
                ('flag', models.CharField(max_length=10)),
                ('demonyms', models.JSONField()),
                ('flags', models.JSONField()),
                ('coat_of_arms', models.JSONField()),
                ('population', models.PositiveIntegerField()),
                ('maps', models.JSONField()),
                ('gini', models.JSONField()),
                ('car', models.JSONField()),
                ('postal_code', models.JSONField()),
                ('start_of_week', models.CharField(max_length=10)),
                ('timezones', models.JSONField()),
                ('currencies', models.ManyToManyField(to='countries.currency')),
            ],
        ),
    ]
