from django.db import models


class Currency(models.Model):
    code = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    symbol = models.CharField(max_length=255)


# TODO: Move all the json values to seperate models progressively.
class Country(models.Model):
    common_name = models.CharField(max_length=100)
    official_name = models.CharField(max_length=100)
    native_name = models.JSONField()
    tld = models.CharField(max_length=10)
    cca2 = models.CharField(max_length=10)
    ccn3 = models.CharField(max_length=10)
    cca3 = models.CharField(max_length=10)
    cioc = models.CharField(max_length=10)
    fifa = models.CharField(max_length=10)
    independent = models.BooleanField()
    status = models.CharField(max_length=100)
    un_member = models.BooleanField()
    idd = models.JSONField()
    capital = models.CharField(max_length=100)
    capital_info = models.JSONField()
    alt_spellings = models.CharField(max_length=10)
    region = models.CharField(max_length=100)
    subregion = models.CharField(max_length=100)
    continents = models.JSONField()
    languages = models.JSONField()
    translations = models.JSONField()
    latlng = models.JSONField()
    landlocked = models.BooleanField()
    borders = models.JSONField()
    area = models.PositiveIntegerField()
    flag = models.CharField(max_length=10)
    demonyms = models.JSONField()
    flags = models.JSONField()
    coat_of_arms = models.JSONField()
    population = models.PositiveIntegerField()
    maps = models.JSONField()
    gini = models.JSONField()
    car = models.JSONField()
    postal_code = models.JSONField()
    start_of_week = models.CharField(max_length=10)
    timezones = models.JSONField()
    currencies = models.ManyToManyField(Currency)
